SET foreign_key_checks = 0;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	`user_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '用户id',
	`usr_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT 'usrId',
	`user_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '用户名',
	`grade` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '段位',
	`total_gain` DECIMAL(15,2) NOT NULL DEFAULT 0.00 COMMENT '总盈利',
	`month_gain` DECIMAL(15,2) NOT NULL DEFAULT 0.00 COMMENT '月盈利',
	`week_gain` DECIMAL(15,2) NOT NULL DEFAULT 0.00 COMMENT '周盈利',
	`daily_gain` DECIMAL(15,2) NOT NULL DEFAULT 0.00 COMMENT '日盈利',
	`success_rate` DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '选股成功率',
	`total_assets` DECIMAL(18,2)  NOT NULL DEFAULT 0.00 COMMENT '总资产',
	`follow` BIGINT(20)  NOT NULL DEFAULT 0 COMMENT '被追踪数',
	`trade_info` VARCHAR(20)  NOT NULL DEFAULT '' COMMENT '今日动态',
	`type` VARCHAR(10)  NOT NULL DEFAULT '' COMMENT '类型',
	`rank_no` INT(5) NOT NULL DEFAULT 0 COMMENT '排名',
	`no_stock` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否空仓 0:不是，1:是',
	`add_time` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT '添加时间',
	`modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
    UNIQUE UNQ_USER_ID(user_id),
	INDEX IDX_ADD_TIME(`add_time`),
	INDEX IDX_MODIFY_TIME(`modify_time`)
) COMMENT='用户信息';

DROP TABLE IF EXISTS user_stock_info;

CREATE TABLE user_stock_info (
    `id` BIGINT (20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` BIGINT (20) NOT NULL DEFAULT 0 COMMENT '用户id',
    `code` VARCHAR (10) NOT NULL DEFAULT '' COMMENT '股票code',
    `name` VARCHAR (10) NOT NULL DEFAULT '' COMMENT '股票名称',
    `hold_num` INT (10) NOT NULL DEFAULT 0 COMMENT '持仓数目',
    `buy_time` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT '买入时间',
    `cost` DECIMAL (10, 2) NOT NULL DEFAULT 0.00 COMMENT '成本',
    `current_price` DECIMAL (10, 2) NOT NULL DEFAULT 0.00 COMMENT '现价',
    `today_increase` DECIMAL (10, 2) NOT NULL DEFAULT 0.00 COMMENT '今日涨幅',
    `market_value` DECIMAL (18, 2) NOT NULL DEFAULT 0.00 COMMENT '持仓市值',
    `increase_rate` DECIMAL (10, 2) NOT NULL DEFAULT 0.00 COMMENT '盈亏率',
    `floating_profit` DECIMAL (18, 2) NOT NULL DEFAULT 0.00 COMMENT '浮动盈亏',
    `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否有效 0:有效，1:无效',
    `add_time` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00' COMMENT '添加时间',
    `modify_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY FOR_USER_ID(`user_id`) REFERENCES user(`user_id`),
    INDEX IDX_CODE(code),
    INDEX IDX_ADD_TIME (add_time),
    INDEX IDX_MODIFY_TIME (modify_time)
) COMMENT = '用户持仓信息';
SET foreign_key_checks = 1;
